/**
 * @fileoverview API response and request payload types (e.g. candidate from backend).
 */

/**
 * Base candidate shape from API (may differ from dashboard ExtendedCandidate).
 */
export interface Candidate {
  id: string;
  firstName: string;
  lastName: string;
  email: string;
  cvUrl: string;
  overallScore?: number;
  evaluationResults?: unknown;
}

/** Parsed CV preview returned after uploading a CV. */
export interface ParsedCv {
  experienceLevel?: string;
  detectedStack?: string[];
  sections?: Record<string, string>;
}

/** Upload CV response, includes parsed data preview and optional R2 storage key. */
export interface UploadCvResponse {
  /** Unique candidate UUID generated by the backend. */
  candidateId: string;
  /** R2 object key where the raw PDF was stored (e.g. "cvs/uuid.pdf"). */
  r2Key?: string;
  /** Structured CV preview parsed by Gemini (experienceLevel, detectedStack, sections). */
  parsed?: ParsedCv;
}

/** Answer submission for candidate evaluation. */
export interface CandidateAnswerPayload {
  questionId: string;
  answerText: string;
}

/** Validate-invitation API response. */
export interface ValidateInvitationResponse {
  valid: boolean;
  message?: string;
  candidateEmail?: string;
  candidateName?: string;
  jobTitle?: string;
  organizationId?: string;
  jobId?: string;
  invitationId?: string;
}

/** Assessment Pipeline: Single cheat event (lockdown violation). */
export interface CheatEventItem {
  eventType: 'tab_switch' | 'copy_attempt' | 'paste_attempt' | 'right_click' | 'fullscreen_exit';
  occurredAt: string; // ISO 8601
  details?: unknown;
}

/** Assessment Pipeline: Extended answer submission format. */
export interface AnswerSubmission {
  questionId: string;
  answerText: string;
  timeSpentSeconds?: number;
}

/** Assessment Pipeline: Submit Evaluation Payload. */
export interface SubmitAssessmentPayload {
  jobId: string;
  sessionId: string;
  invitationId: string;
  submissionType: 'manual' | 'timer_expired';
  answers: AnswerSubmission[];
  cheatEvents: CheatEventItem[];
}

/** Assessment Pipeline: Response for starting an exam session. */
export interface StartSessionResponse {
  sessionId: string;
  status: string;
}

/** Transcript: Single interview question and candidate's graded answer. */
export interface TranscriptItem {
  questionText: string;
  questionType: string;
  sampleAnswer: string;
  redactedAnswer: string;
  score: number;
  feedback: string;
  hfGatePassed: boolean;
  wasFlagged: boolean;
}

/** Transcript: Full candidate interview transcript response. */
export interface TranscriptResponse {
  candidateId: string;
  candidateName: string;
  candidateEmail: string;
  jobTitle: string;
  appliedDate: string;
  overallScore: number;
  cvScore: number;
  skillsScore: number;
  interviewScore: number;
  summaryFeedback: string;
  transcript: TranscriptItem[];
  education?: string | Array<Record<string, string>>;
  workExperience?: string | Array<Record<string, string>>;
  projects?: string | Array<Record<string, string>>;
  technicalSkills?: string | string[];
  achievements?: string | Array<Record<string, string>>;
  certificates?: string | Array<Record<string, string>>;
  phone?: string;
}